server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## ????? ??? ??
spring:
  application:
    name: apigateway-service

  datasource:
    url: jdbc:mysql://localhost:3306/learnauth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none ? ??)
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9001/
          predicates:
            - Path=/user/**
        - id: lecture-service
          uri: http://localhost:9002/
          predicates:
            - Path=/lecture/**
        - id: report-service
          uri: http://localhost:9003/
          predicates:
            - Path=/report/**


management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
