server:
  port: ${PORT}
#
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 172.19.0.3
      port: 6379
      password: ${REDIS_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}

  encryption:
    key: ${AES_256}

  server:
    forward-headers-strategy: NATIVE
    tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

springdoc:
  server:
    url: https://j12d210.p.ssafy.io

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
#logging:
#  level:
#    root: DEBUG

blockchain:
  rpc:
    url: https://rpc-amoy.polygon.technology/
  relayer:
    private-key: ${BC_PRIVATE_KEY}
  forwarder:
    address: ${BC_FORWARDER}
  cat-token:
    address: ${BC_TOKEN}
  lecture-system:
    address: ${BC_LECTURE}